stages:
  - build
  - deploy

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind

variables:
  APPLICATION_NAME: line-bot
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  DOCKER_IMAGE_TAGGED: ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_INGRESS_HOST: linebot.maximemoreillon.com

build:
  stage: build
  tags:
    - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin

  script:
    # Build and push docker image
    - docker build -t ${DOCKER_IMAGE} .
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAGGED}
    - docker push ${DOCKER_IMAGE}
    - docker push ${DOCKER_IMAGE_TAGGED}

deploy:
  stage: deploy
  tags:
    - dind
  only:
    - master
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s/kubernetes-agent:cloud
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
