apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-bot
  template:
    metadata:
      labels:
        app: line-bot
    spec:
      containers:
      - name: line-bot
        image: 192.168.1.2:5000/line-bot
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: line-bot
  name: line-bot
spec:
  ports:
  - port: 8087
    nodePort: 30087
  selector:
    app: line-bot
  type: LoadBalancer
